---
apiVersion: v1
kind: Pod
metadata:
 name: multiple
spec:
 containers:
 - image: nginx
   name: nginx
   ports:
    - containerPort: 80
 - image: almalinux
   name: almalinux
   command: ["sleep", "200"]