apiVersion: v1
kind: Pod
metadata:
  name: label-pod
  labels:
    course: docker
    duration: 25hr
    trainer: siva
  annotations:
    org.docker.kubernetes.image.maintainer: siva
spec:
  containers:
  - name: nginx
    image: nginx