kind: Namespace
apiVersion: v1
metadata:
  name: roboshop
  labels:
    name: roboshop
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop
  name: roboshop-admin-role
rules:
- apiGroups: ["*"] # "" indicates the core API group and this has access everything on roboshop name which we created in IAM
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: roboshop-admin-rolebinding
  namespace: roboshop
subjects:
- kind: User
  name: roboshop-admin   # This is the User which we created in IAM and gave policy
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: roboshop-admin-role
  apiGroup: rbac.authorization.k8s.io